application: login-template
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js/(.*\.js)
  mime_type: application/javascript
  static_files: js/\1
  upload: js/(.*\.js)

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /html
  static_dir: html

- url: .*
  script: index.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
