application: login-template-server
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /html
  static_dir: html
  application_readable: true

- url: .*
  script: index.application

libraries:
- name: webapp2
  version: latest

- name: pycrypto
  version: "2.6"